"""init

Revision ID: 4ea6dd5931b5
Revises: 
Create Date: 2025-10-04 17:32:13.360697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ea6dd5931b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ACTIVE', 'PENDING', 'REJECTED', name='userstatus').create(op.get_bind())
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('user_type', postgresql.ENUM('VIEWER', 'STREAMER', 'SUPER_ADMIN', name='userrole', create_type=False), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'PENDING', 'REJECTED', name='userstatus', create_type=False), nullable=False),
    sa.Column('credibility', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    sa.Enum('ACTIVE', 'PENDING', 'REJECTED', name='userstatus').drop(op.get_bind())
    # ### end Alembic commands ###
