"""add streamer profile

Revision ID: 789b25ef6a6f
Revises: 4ea6dd5931b5
Create Date: 2025-10-04 18:42:19.228840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789b25ef6a6f'
down_revision: Union[str, None] = '4ea6dd5931b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streamer_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel_name', sa.String(length=20), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('url_stream', sa.String(length=1024), nullable=False),
    sa.Column('banner_url', sa.String(length=1024), nullable=True),
    sa.Column('min_amount_challenge', sa.Integer(), nullable=False),
    sa.Column('disable_challenges', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streamer_profiles')),
    sa.UniqueConstraint('channel_name', name=op.f('uq_streamer_profiles_channel_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streamer_profiles')
    # ### end Alembic commands ###
