"""init

Revision ID: 2a958bc46678
Revises:
Create Date: 2026-01-11 13:27:37.437857

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a958bc46678"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("VIEWER", "STREAMER", "SUPER_ADMIN", name="role").create(op.get_bind())
    op.create_table(
        "challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "streamer_fixed_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "STREAMER_ACCEPTED",
                "STREAMER_REJECTED",
                "STREAMER_COMPLETED",
                "VIEWER_CONFIRMED",
                "VIEWER_REJECTED",
                "REFUNDED",
                "DONE",
                name="challengestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.create_table(
        "streamers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "min_amount_challenge", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("disable_challenges", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streamers")),
        sa.UniqueConstraint("user_id", name=op.f("uq_streamers_user_id")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "VIEWER", "STREAMER", "SUPER_ADMIN", name="role", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("credibility", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    sa.Enum("VIEWER", "STREAMER", "SUPER_ADMIN", name="userrole").drop(op.get_bind())
    sa.Enum("ACTIVE", "PENDING", "REJECTED", name="userstatus").drop(op.get_bind())
    sa.Enum("DONE_CHALLENGE_FEE", "FAIL_CHALLENGE_FEE", name="challengefee").drop(
        op.get_bind()
    )
    op.sync_enum_values(
        enum_schema="public",
        enum_name="challengestatus",
        new_values=[
            "PENDING",
            "STREAMER_ACCEPTED",
            "STREAMER_REJECTED",
            "STREAMER_COMPLETED",
            "VIEWER_CONFIRMED",
            "VIEWER_REJECTED",
            "REFUNDED",
            "DONE",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="challenges", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="challengestatus",
        new_values=[
            "PENDING",
            "ACCEPTED",
            "STREAMER_REJECTED",
            "STREAMER_COMPLETED",
            "VIEWER_CONFIRMED",
            "VIEWER_REJECTED",
            "REFUNDED",
            "DONE",
        ],
        affected_columns=[
            TableReference(
                table_schema="public", table_name="challenges", column_name="status"
            )
        ],
        enum_values_to_rename=[],
    )
    sa.Enum("DONE_CHALLENGE_FEE", "FAIL_CHALLENGE_FEE", name="challengefee").create(
        op.get_bind()
    )
    sa.Enum("ACTIVE", "PENDING", "REJECTED", name="userstatus").create(op.get_bind())
    sa.Enum("VIEWER", "STREAMER", "SUPER_ADMIN", name="userrole").create(op.get_bind())
    op.drop_table("wallets")
    op.drop_table("users")
    op.drop_table("streamers")
    op.drop_table("challenges")
    sa.Enum("VIEWER", "STREAMER", "SUPER_ADMIN", name="role").drop(op.get_bind())
    # ### end Alembic commands ###
