"""create transation and ledger entry

Revision ID: 0c4faabaaacf
Revises: 2a958bc46678
Create Date: 2026-01-11 14:03:31.910633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c4faabaaacf"
down_revision: Union[str, None] = "2a958bc46678"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "DEPOSIT",
        "WITHDRAW",
        "TRANSFER",
        "ESCROW_LOCK",
        "ESCROW_RELEASE",
        name="transaction_type",
    ).create(op.get_bind())
    sa.Enum("BANK", "USER_WALLET", "ESCROW", "COMMISSION", name="account_type").create(
        op.get_bind()
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            postgresql.ENUM(
                "DEPOSIT",
                "WITHDRAW",
                "TRANSFER",
                "ESCROW_LOCK",
                "ESCROW_RELEASE",
                name="transaction_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM(
                "BANK",
                "USER_WALLET",
                "ESCROW",
                "COMMISSION",
                name="account_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("debit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_ledger_entries_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_entries")
    op.drop_table("transactions")
    sa.Enum("BANK", "USER_WALLET", "ESCROW", "COMMISSION", name="account_type").drop(
        op.get_bind()
    )
    sa.Enum(
        "DEPOSIT",
        "WITHDRAW",
        "TRANSFER",
        "ESCROW_LOCK",
        "ESCROW_RELEASE",
        name="transaction_type",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
