"""init

Revision ID: ca5ab9553bb9
Revises:
Create Date: 2026-03-14 20:31:43.262420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ca5ab9553bb9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "PENDING",
        "STREAMER_ACCEPTED",
        "STREAMER_REJECTED",
        "STREAMER_COMPLETED",
        "VIEWER_CONFIRMED",
        "VIEWER_REJECTED",
        "FAIL",
        "DONE",
        name="challengestatus",
    ).create(op.get_bind())
    sa.Enum("VIEWER", "STREAMER", "ADMIN", "SUPER_ADMIN", name="role").create(
        op.get_bind()
    )
    sa.Enum("CHALLENGE", "DONATE", "COMPETITIVE", name="product_type").create(
        op.get_bind()
    )
    sa.Enum(
        "DEPOSIT",
        "WITHDRAW",
        "TRANSFER",
        "ESCROW_LOCK",
        "ESCROW_RELEASE",
        "POOL_DEPOSIT",
        "POOL_RELEASE",
        name="transaction_type",
    ).create(op.get_bind())
    sa.Enum(
        "BANK", "USER_WALLET", "ESCROW", "POOL", "REVENUE", name="account_type"
    ).create(op.get_bind())
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expiration", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
    )
    op.create_table(
        "challenges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("assigned_to", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fee", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "streamer_fixed_amount", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "STREAMER_ACCEPTED",
                "STREAMER_REJECTED",
                "STREAMER_COMPLETED",
                "VIEWER_CONFIRMED",
                "VIEWER_REJECTED",
                "FAIL",
                "DONE",
                name="challengestatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_challenges")),
    )
    op.create_table(
        "streamers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "min_amount_challenge", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("disable_challenges", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.UUID(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_streamers")),
        sa.UniqueConstraint("user_id", name=op.f("uq_streamers_user_id")),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "transaction_type",
            postgresql.ENUM(
                "DEPOSIT",
                "WITHDRAW",
                "TRANSFER",
                "ESCROW_LOCK",
                "ESCROW_RELEASE",
                "POOL_DEPOSIT",
                "POOL_RELEASE",
                name="transaction_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "payer_type",
            postgresql.ENUM(
                "BANK",
                "USER_WALLET",
                "ESCROW",
                "POOL",
                "REVENUE",
                name="account_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("payer_id", sa.UUID(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("reference_id", sa.UUID(), nullable=False),
        sa.Column(
            "reference_type",
            postgresql.ENUM(
                "CHALLENGE",
                "DONATE",
                "COMPETITIVE",
                name="product_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "VIEWER",
                "STREAMER",
                "ADMIN",
                "SUPER_ADMIN",
                name="role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("credibility", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("balance", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wallets")),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column(
            "account_type",
            postgresql.ENUM(
                "BANK",
                "USER_WALLET",
                "ESCROW",
                "POOL",
                "REVENUE",
                name="account_type",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("account_id", sa.UUID(), nullable=True),
        sa.Column("debit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("credit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_ledger_entries_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ledger_entries")
    op.drop_table("wallets")
    op.drop_table("users")
    op.drop_table("transactions")
    op.drop_table("streamers")
    op.drop_table("challenges")
    op.drop_table("auth_sessions")
    sa.Enum(
        "BANK", "USER_WALLET", "ESCROW", "POOL", "REVENUE", name="account_type"
    ).drop(op.get_bind())
    sa.Enum(
        "DEPOSIT",
        "WITHDRAW",
        "TRANSFER",
        "ESCROW_LOCK",
        "ESCROW_RELEASE",
        "POOL_DEPOSIT",
        "POOL_RELEASE",
        name="transaction_type",
    ).drop(op.get_bind())
    sa.Enum("CHALLENGE", "DONATE", "COMPETITIVE", name="product_type").drop(
        op.get_bind()
    )
    sa.Enum("VIEWER", "STREAMER", "ADMIN", "SUPER_ADMIN", name="role").drop(
        op.get_bind()
    )
    sa.Enum(
        "PENDING",
        "STREAMER_ACCEPTED",
        "STREAMER_REJECTED",
        "STREAMER_COMPLETED",
        "VIEWER_CONFIRMED",
        "VIEWER_REJECTED",
        "FAIL",
        "DONE",
        name="challengestatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
